fix(recovery): update the process of recovery and state-update
fix #flato-2358

feat(*): update unit test

fix(*): remove initial check state and update the unit tests

fix(pre-commit): update pre-commit

fix(*): fix functions, updateHighStateTarget, tryStateTransfer, msgToEvent

updateHighStateTarget has to reject nil target, tryStateTransfer will always transfer to the high
state, the abnormal event of msgToEvent should be sent by goroutine as it will be triggered in main
listener

fix(*): add TODO for safe stop

fix(*): do some changes according to review

1) add TODO to stop metrics;
2) clear notification messages from lower epoch at start of sending notification;
3) we only need to stop recoveryRestartTimer before we tigger a initRecovery to find correct view-number after epoch-changed in state-update

fix(*): update some comments

update the comments of compareWholeStates

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,29 +3,28 @@ cd $GOPATH/src/github.com/ultramesh/flato-rbft
 
 st=0
 counter=0
-echo "1. gometalint.."
-for pkg in $(go list ./... | grep -v /vendor/); do
-    # echo "gometalinter ==> $pkg:"
-    # gometalinter  "$pkg"
-    rest=`gometalinter "$pkg"`
-    if [[ ! -z $rest ]]; then
-      # st=1;
-      # because of pn.go lint will never passed
-      echo "$rest" | grep -v '.pb.go'
-      counter=$((counter+1)) ;
-      if [[ $counter -gt 10 ]]; then
-         # exit 1;
-         echo "too many gometalinter error..."
-         break;
-      fi
-    fi
-done
-[ $st -ne 0 ] && exit 1
-
-echo "2. gofmt.."
+echo "1. gofmt.."
 find . -path '*/vendor/*' -prune -o -name '*.go' -type f -exec gofmt -s -w {} \;
 [ $? -ne 0 ] && exit 1
 
+echo "2. golangci-lint run.."
+#for pkg in $(go list ./... | grep -v /vendor/); do
+#    # echo "golangci-lint run ==> $pkg:"
+#    golangci-lint run
+#    rest=`golangci-lint run`
+#    if [[ ! -z $rest ]]; then
+#      # st=1;
+#      # because of pn.go lint will never passed
+#      echo "$rest" | grep -v '.pb.go'
+#      counter=$((counter+1)) ;
+#      if [[ $counter -gt 10 ]]; then
+#         exit 1;
+#         echo "too many golangci-lint run error..."
+#         break;
+#      fi
+#    fi
+#done
+#[ $st -ne 0 ] && exit 1
+
 # add formatted files
 git add -u
-
